name: Run Doc Examples

on:
  # trigger on pull requests
  pull_request:

  # trigger on all commits to main
  push:
    branches:
      - 'main'

  # trigger on request
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python: ['3.12']
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.2.1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@3573ddaebf3290e00bfb150b82a46412192a61d3
      with:
        # only-binary: ":none:"
        lockfile: ".github/requirements${{ matrix.python }}.txt"
    - name: Install package
      run: |
        python --version
        uv pip install . --no-build-isolation --no-deps --system -v
    - name: Extract Documentation Code
      run: |
        awk > '
              /```python/ {in_block=1; file="README_code_block_" ++count ".py"; next}
              /```/ {in_block=0; next}
              in_block {print > file}
              '
              README.md
    - name: Test Documentation Code
      run: for f in README_code*.py; do python3 "$f"; done && echo OK
